class Urls:
    MAIN_PAGE = 'https://stellarburgers.nomoreparties.site/'
    LOGIN_PAGE = 'https://stellarburgers.nomoreparties.site/login'
    REGISTER_USER = 'https://stellarburgers.nomoreparties.site/api/auth/register'
    DELETE_USER = 'https://stellarburgers.nomoreparties.site/api/auth/user'
    PROFILE_PAGE = 'https://stellarburgers.nomoreparties.site/account/profile'
    FORGOT_PASSWORD_PAGE = 'https://stellarburgers.nomoreparties.site/forgot-password'
    RESET_PASSWORD_PAGE = 'https://stellarburgers.nomoreparties.site/reset-password'
    ORDERS_HISTORY = 'https://stellarburgers.nomoreparties.site/account/order-history'
    FEED = 'https://stellarburgers.nomoreparties.site/feed'
